### ISSUE TITLE
Broken functionality

### ISSUE THREAD

**Issue by totaler** [gisce/libComXML#49]
Version 3.0.0 breaks funcionality when working with str chunks. Since version 2.2.3 it worked fine.

It means that when passing an xml as str converted it ignores it when building xml file.

**Comment by ecarreras** [comment]
Yes, we're working on it. Maybe we can ensure that requirements enforces use `<3.0`

**Comment by ecarreras** [comment]
This https://github.com/gisce/libComXML/pull/53 fix this issue
